mtprotosender.py:228 #INFO     [2025-09-24 16:15:08,282] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
mtprotosender.py:279 #INFO     [2025-09-24 16:15:08,360] - telethon.network.mtprotosender - 0| Connection to 149.154.167.51:443/TcpFull complete!
handlers.py:15 #INFO     [2025-09-24 16:15:16,831] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:15 #INFO     [2025-09-24 16:16:26,382] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:15 #INFO     [2025-09-24 16:16:38,575] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:15 #INFO     [2025-09-24 16:17:09,323] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:15 #INFO     [2025-09-24 16:17:09,325] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
mtprotosender.py:319 #INFO     [2025-09-24 16:17:15,075] - telethon.network.mtprotosender - 0| Disconnecting from 149.154.167.51:443/TcpFull...
mtprotosender.py:339 #INFO     [2025-09-24 16:17:15,076] - telethon.network.mtprotosender - 0| Disconnection from 149.154.167.51:443/TcpFull complete!
base_events.py:1758 #ERROR    [2025-09-24 16:17:15,109] - asyncio - 0| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000265FCFF9330>
