mtprotosender.py:228 #INFO     [2025-10-02 14:48:38,796] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
mtprotosender.py:279 #INFO     [2025-10-02 14:48:38,905] - telethon.network.mtprotosender - 0| Connection to 149.154.167.51:443/TcpFull complete!
handlers.py:17 #INFO     [2025-10-02 14:48:43,180] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:17 #INFO     [2025-10-02 14:48:46,603] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:17 #INFO     [2025-10-02 14:48:46,606] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:17 #INFO     [2025-10-02 14:48:47,702] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
mtprotosender.py:319 #INFO     [2025-10-02 14:48:49,210] - telethon.network.mtprotosender - 0| Disconnecting from 149.154.167.51:443/TcpFull...
mtprotosender.py:339 #INFO     [2025-10-02 14:48:49,211] - telethon.network.mtprotosender - 0| Disconnection from 149.154.167.51:443/TcpFull complete!
base_events.py:1758 #ERROR    [2025-10-02 14:48:49,282] - asyncio - 0| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000027D94E26440>
