mtprotosender.py:228 #INFO     [2025-09-29 12:27:27,203] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
mtprotosender.py:279 #INFO     [2025-09-29 12:27:27,287] - telethon.network.mtprotosender - 0| Connection to 149.154.167.51:443/TcpFull complete!
handlers.py:167 #INFO     [2025-09-29 12:27:32,190] - root - 0| Handler called. MessageEdited
handlers.py:167 #INFO     [2025-09-29 12:28:28,139] - root - 0| Handler called. MessageEdited
mtprotosender.py:319 #INFO     [2025-09-29 12:28:31,735] - telethon.network.mtprotosender - 0| Disconnecting from 149.154.167.51:443/TcpFull...
mtprotosender.py:339 #INFO     [2025-09-29 12:28:31,736] - telethon.network.mtprotosender - 0| Disconnection from 149.154.167.51:443/TcpFull complete!
base_events.py:1758 #ERROR    [2025-09-29 12:28:31,767] - asyncio - 0| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D666D72380>
